name: recipy_frontend
description: Frontend application for the Recipy Project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.5
  logging: ^1.2.0
  intl: ^0.18.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter_keyboard_visibility: ^5.4.1
  beamer: ^1.5.5
  image_picker: ^0.8.7
  easy_localization: ^3.0.2
  carousel_slider: ^4.2.1
  http_parser: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.10
  freezed: ^2.0.0
  json_serializable: ^6.1.6
  flutter_launcher_icons: ^0.13.1

analyzer:
  errors:
    invalid_annotation_target: ignore

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_foreground: "assets/app_logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/translations/
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
